### ISSUE TITLE
Sequoia 15.1 Beta 5

### ISSUE THREAD

**Issue by tateu** [luckman212/screencapture-nag-remover#1]
Neither the MDM profile (manually installed on a computer not connected to an MDM Server) nor the ScreenCaptureApprovals.plist (kScreenCaptureApprovalLastAlerted, kScreenCaptureApprovalLastUsed) method work.

Steps

1. open Terminal
2. type "screencapture test.png"
3. Set Terminal as allowed to Record Screen in Privacy Settings
4. Restart Terminal
5. type "screencapture test.png"
6. Click "Continue to allow"
7. run screencapture-nag-remover using plist method
8. run screencapture-nag-remover to install MDM profile
9. Set computer date forward 2 months
10. type "screencapture test.png"

I still get a popup saying "Terminal is requesting to bypass the system private window picker..."

What I have found, and this works without even using screencapture-nag-remover, is that I always get 30 days without the "continue to allow" popup from whenever the last time I tried to do a screencapture with a specific App.

Steps

1. open Terminal
2. type "screencapture test.png"
3. Works without popup
4. Set computer date 20 days ahead
5. type "screencapture test.png"
6. Works without popup
7. Set computer date another 20 days ahead
8. type "screencapture test.png"
9. Works without popup
10. Set computer date another 20 days ahead
11. type "screencapture test.png"
12. Works without popup

I am now 2 months in the future without receiving another popup because I always used screencapture within the 30 day window before the popup is required, which resets and gives me another 30 days.

**Comment by luckman212** [comment]
Thanks for the report. I'll try to reproduce this on my 15.1 test Mac and see if I can figure out why it's not working for you.

**Comment by tateu** [comment]
Ok, I see I missed writing a step in my original post.  It works correctly (sort of) if following the steps in my original post or the steps in your post.

I missed step 4 below.  After running screencapture-nag-remover but before setting the date forward, run screencapture test.png again.

1. Run screencapture test.png to trigger the Alert
2. Run screencapture-nag-remover.sh and choose N (don't install the profile)
3. The script will proceed to run the fix in "legacy mode"
4. Run screencapture test.png again (before changing the date)
5. Set computer date forward 2 months
6. Run screencapture test.png
7. You will get an alert

Every time you run "screencapture test.png", it changes the date for kScreenCaptureApprovalLastUsed which resets the value changed by  screencapture-nag-remover, thus resetting the popup to happen again 30 days from now.

In order for this method to work, literally every time you run a screencapture, you have to run screencapture-nag-remover after again.

**Comment by luckman212** [comment]
My research seems to indicate that these types of TCC config profiles can only be installed on a fully MDM-joined computer, and must be pushed from the server. See error below

<img width="384" alt="image" src="https://github.com/user-attachments/assets/024d7acd-6fb4-4c99-91a8-7974972757f0">

@tateu I've released a [new version][1] that no longer tries to use this method, and it should work properly. Please give it a try!

[1]: https://github.com/luckman212/screencapture-nag-remover/releases/tag/1.2.0

**Comment by luckman212** [comment]
@tateu I tested further, you're right it seems that after each invocation, replayd is setting the timestamp in the plist and causing a re-prompt to appear if the date is set >1 month ahead. I am not sure how to solve this other than setting up a small LaunchAgent to run periodically and constantly push the date forward.

**Comment by tateu** [comment]
I am definitely not happy with Apple over the past few years.  I don't like their new M Series computers.  Well, I like them but the GPU is unusable for my use case...it cannot keep multiple video outputs in frame sync like the AMD Radeon GPUs on the Intel Macs.  This will end up killing my business and putting me out of work in a few years.

Now, this stupid decision with a monthly popup???  I run these computers remotely and rely on automated screen capture and automated analysis of the screen capture to notify me of possible issues.

For the moment, since my screen captures run everyday, which resets the popup date and continuously gives me another 30 days without it...I can live with it, as is.

**Comment by luckman212** [comment]
I'm going to try the LaunchAgent method. Stay tuned.

**Comment by luckman212** [comment]
@tateu Please give [v1.3.0][1] a try (use `--install` to install the LaunchAgent)

[1]: https://github.com/luckman212/screencapture-nag-remover/releases/tag/1.3.0

**Comment by tateu** [comment]
Seems good.  It didn't originally look like launchd was running the script every 24 hours but I think that was an issue caused by me. I was doing some other testing and stuff on the computer that may have interfered.

But I booted up and ran it again last night at 9pm and, tonight at 9pm, launchd ran the script.

The only thing I don't know...is how launchd handles things when the computer has been off for more than 24 hours.  Does it run the script immediately at boot, or does it wait for the 24 hour period to roll around again?

If it waits...it may be worthwhile to add ```<key>RunAtLoad</key><true/>``` to the LaunchAgent plist.

**Comment by luckman212** [comment]
According to [launchd.info](https://www.launchd.info/#/key-StartInterval) which is the "unofficial official" source:

> _If the system is asleep, **the job will be started the next time the computer wakes up**. If multiple intervals transpire before the computer is woken, those events will be coalesced into one event upon wake from sleep._

I believe the same would apply if the computer was powered off when the interval elapsed.

**Comment by luckman212** [comment]
@tateu How are things working? Can this be considered closed?

**Comment by tateu** [comment]
Yes, I think we're good. It auto ran successfully again tonight at 9pm.  I can't test leaving my computer off for 24 hours but I'll assume the quote above is correct.
